### ISSUE TITLE
Any plan for updating the GraphQL.Client to the latest version?

### ISSUE THREAD

**Issue by alyyasser** [charlesdevandiere/graphql-client-extensions#28]
HI, is there any plan to update the GraphQL.Client to latest version (3.x.x)?

**Comment by charlesdevandiere** [comment]
@alyyasser, it is under study.

Thanks for your interest !

**Comment by charlesdevandiere** [comment]
@alyyasser I'm not sure that GraphQL.Client.Extensions has a lot of interest with GraphQL.Client `3.x.x`. GraphQL.Client.Extensions provides automatic conversion of the response into a C# object. But since version 2, GraphQL.Client allows it natively.

If you want to use GraphQL query generation, you can use [GraphQL.Query.Builder](https://github.com/charlesdevandiere/graphql-query-builder-dotnet) as GraphQL.Client.Extensions does.

I will update the GraphQL.Query.Builder [sample](https://github.com/charlesdevandiere/graphql-query-builder-dotnet/tree/master/sample) using the latest version of GraphQL.Client as soon as possible.

**Comment by charlesdevandiere** [comment]
@alyyasser the [sample](https://github.com/charlesdevandiere/graphql-client-extensions/tree/master/sample/Pokedex) is up to date.

I hope you find it useful !

**Comment by reureu** [comment]
Hi guys,

Sorry for putting my two pennies in an issue that is already closed.

One of the advantage of using a more recent version of GraphQL.Client would be to get rid of an indirect dependency on GraphQL.Common.

GraphQL.Client 1.x depends on GraphQL.Common. GraphQL.Common is legacy and no longer maintained.
Since GraphQL.Client 2.x, this dependency on GraphQL.Common was removed.

I think it would be a good idea to update GraphQL.Client.Extensions to a more recent release of GraphQL.Client, so that it no longer relies on obsolete libraries. It would probably the maintenance of this library easier in the future.

Kind regards,
Reureu
